---
- hosts: all
  tasks:
    - name: Load encrypted vars file
      community.sops.load_vars:
        file: group_vars/all.sops.yml
    - include_tasks: "{{ task }}"
      loop:
        - "{{ playbook_dir }}/tasks/apt_sources.yml"
        - "{{ playbook_dir }}/tasks/apt_packages.yml"
        - "{{ playbook_dir }}/tasks/dotfiles.yml"
      loop_control:
        loop_var: task
