---
- name: add Google Cloud SDK APT source
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: goole-cloud-sdk

- name: add Kubernetes APT source
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: k8s

- name: add Google APT signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add regolith APT source
  apt_repository:
    repo: 'ppa:regolith-linux/release'
    state: present

- name: add Yubico APT source
  apt_repository:
    repo: 'ppa:yubico/stable'
    state: present

