---
- name: SNAP | install packages
  become: yes
  snap:
    name: "{{ snap_pkg }}"
    classic: yes
    state: present
  loop:
    - spotify
    - slack
    - code
  loop_control:
    loop_var: snap_pkg
